### ISSUE TITLE
Add a twitter card

### ISSUE THREAD

**Issue by Mackenzie-OO7** [Consensys/doc.zk-evm#113]
The Linea documentation does not have a preview card

![Screenshot 2023-06-10 114353](https://github.com/ConsenSys/doc.zk-evm/assets/97461848/6991fc4b-ea0d-4163-9bc6-464940a81f1d)

Please provide me with a link to the Linea logo so I can add it to the configuration file.
Thank you.

**Comment by jlwllmr** [comment]
Thanks, we addressed this at long last in #486.
