### ISSUE TITLE
Etherscan link missing

### ISSUE THREAD

**Issue by mapachurro** [Consensys/doc.zk-evm#150]
## Describe the bug

In the [Message Service documentation](https://docs.linea.build/developers/bridge-architecture/message-service#workflow), we're missing a link to Etherscan:

![image](https://github.com/ConsenSys/doc.zk-evm/assets/7252642/84d86108-c0ab-427d-a85d-79a24215f610)

## System settings

- OS and version: windows 11
- Browser and version: chrome, current
- Plugins activated in your browser: MM

**Comment by jlwllmr** [comment]
This seems to have been fixed — the line of text was removed at some point. 

<img width="739" alt="image" src="https://github.com/Consensys/doc.zk-evm/assets/95916148/ea3964b6-05ca-43ea-9382-22cc79072814">
