### ISSUE TITLE
Error: You must specify a network_id in your 'consensys-zkevm-goerli' configuration in order to use this network.

### ISSUE THREAD

**Issue by roo-shy** [ConsenSys/doc.zk-evm#26]
## Error: You must specify a network_id in your 'consensys-zkevm-goerli' configuration in order to use this network.

When following this page: https://docs.zkevm.consensys.net/developers/quickstart/deploy-smart-contract/truffle 

3. adding `truffle-config.js`: 

```
require("dotenv").config();
const { MNEMONIC, INFURA_API_KEY } = process.env;

const HDWalletProvider = require("@truffle/hdwallet-provider");

module.exports = {
  networks: {
    consensyszkevmgoerli: {
      provider: () => {
        return new HDWalletProvider(
          MNEMONIC,
          `https://consensys-zkevm-goerli-prealpha.infura.io/v3/${INFURA_API_KEY}`,
        );
      },
      network_id: "59140",
    },
  },
  // ... rest of truffle-config.js
};
```
After calling `truffle migrate --network consensys-zkevm-goerli` from the CLI I hit: 

`Error: You must specify a network_id in your 'consensys-zkevm-goerli' configuration in order to use this network.`

When updating network in truffle config: 

```
 networks: {
    'consensys-zkevm-goerli': {
```
I was able to deploy the contract

## System settings

- OS 
- Brave

**Comment by roo-shy** [comment]
Related to this[ PR](https://github.com/ConsenSys/doc.zk-evm/pull/24) ?

**Comment by Ezzahhh** [comment]
This should probably be assigned to the zkevm team. Same as the other issue.

**Comment by emilyJLin95** [comment]
this PR fixes the issue: https://github.com/ConsenSys/doc.zk-evm/pull/24
