### ISSUE TITLE
Ensure consistency between navigation bar titles and page titles

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/doc.zk-evm#436]
There are instances within the documentation where there is a discrepancy between the titles displayed in the navigation bar and the actual titles on the pages. This inconsistency can lead to confusion for users as they navigate through our documentation.

For example: https://docs.linea.build/build-on-linea/tooling/data-indexers/noves

**Comment by Viktor110** [comment]
> There are instances within the documentation where there is a discrepancy between the titles displayed in the navigation bar and the actual titles on the pages. This inconsistency can lead to confusion for users as they navigate through our documentation.
> 
> 
> 
> For example: https://docs.linea.build/build-on-linea/tooling/data-indexers/noves

**Comment by bgravenorst** [comment]
Closed by https://github.com/Consensys/doc.zk-evm/pull/447

**Comment by bgravenorst** [comment]
Closed by https://github.com/Consensys/doc.zk-evm/pull/447

**Comment by bgravenorst** [comment]
Closed by https://github.com/Consensys/doc.zk-evm/pull/447
