### ISSUE TITLE
Please add a note about rate limiting on https://rpc.goerli.linea.build 

### ISSUE THREAD

**Issue by roo-shy** [ConsenSys/doc.zk-evm#44]
> What is the right RPC endpoint for deploying on linea can anyone confirm, please? A few people are confused about infura account they don't see linea endpoint there, it's only available for private beta participants.

https://rpc.goerli.linea.build/ is rate-limited. If users are existing dapps that will collect a reasonable amount of requests, is better to use infura and `reach out Marco on telegram so that he can enable Linea endpoint in Infura for them` (not sure about contacting part please correct :) )

**Comment by arcxteam** [comment]
I think manual rpc adding is good too, yeah like me i use from pre-alpha consensys zkevm. No limit help on infura dashboard, parameter available
