### ISSUE TITLE
Update Landing page cards

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/doc.zk-evm#451]
Text in the cards on the Linea docs landing page becomes invisible when selected.

![Screenshot 2024-02-28 at 4 15 11 pm](https://github.com/Consensys/doc.zk-evm/assets/50852695/e1ec55a3-063b-41e5-820d-c4fa97936213)

**Comment by mapachurro** [comment]
@sammysango: Don't know if you've seen this / addressed it, yet

**Comment by sammysango** [comment]
@mapachurro I think this has already been fixed...? I can't seem to reproduce it

**Comment by bgravenorst** [comment]
Hi, yes I think I fixed this when I updates the Homepage to use sentence case. Apologies, I should have referenced this issue.

**Comment by sammysango** [comment]
Ah excellent, no problem and thank you for sorting!
