### ISSUE TITLE
Run a Linea node - Edge nodes

### ISSUE THREAD

**Issue by bradbown** [Consensys/doc.zk-evm#466]
The boot nodes listed on [this page](https://docs.linea.build/build-on-linea/run-a-node/use-binary) in [Step 5. Start the Geth client](https://docs.linea.build/build-on-linea/run-a-node/use-binary#step-5-start-the-geth-client) for **testnet** are incorrect and need to be updated.

Old: 
```
--bootnodes "enode://c7d29d1bbb768e73c6bd320608276dc2341670822ed1292456a7b8375de35b5348e3b6bac63783a53d697378b25c5658681683f7621e31b37c605993c5ee13bd@18.189.141.200:30303,enode://14ba040dd8c5b1ea607fabf98c3c7c398658f897c502d0ca5202dce8907e83be953995ce5c3f72def2af710c072fe38de4e9347a299370fc82d6d17819967c93@3.144.118.88:30303" \
```
New:
```
--bootnodes "enode://700f0d5a5f2beadc307b7b8f1a251f8b75033c8222ca65bfb1aecc4c4a0a86d6d6ef8420e780f6ace7cc3d1b837606b116109cc53b00931d3debc1346b9ccbb8@13.51.255.207:31001,enode://cbbaacaf47a005cb389b40f6676d63800cc65295aad0983e5ce9f2e5bf805274cded5ef313993a2564591d6caab6322c2a39a0b3a21143034378179c7d5ecd44@3.16.167.169:31001"
```

**Comment by jlwllmr** [comment]
@bradbown it looks like Chris did fix this — closing. Feel free to reopen if something isn't right! 

<img width="984" alt="image" src="https://github.com/Consensys/doc.zk-evm/assets/95916148/607d351a-77ad-4beb-a47c-c5ff1d3a1726">
