### ISSUE TITLE
linea rpc not working properly

### ISSUE THREAD

**Issue by crossxx-labs** [Consensys/doc.zk-evm#514]
As described here: https://docs.linea.build/reference/api/linea-estimategas and here: https://docs.linea.build/build-on-linea/gas-fees

`curl https://rpc.linea.build \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","method":"linea_estimateGas","params":[{"from":"0x42c27251C710864Cf76f1b9918Ace3E585e6E21b","gasPrice":"0x100000000","gas":"0x21000"}],"id":53}'`

Correct response should be like:
`
{
  "jsonrpc": "2.0",
  "id": 53,
  "result": {
    "baseFeePerGas": "0x7",
    "gasLimit": "0xcf08",
    "priorityFeePerGas": "0x43a82a4"
  }
}
`

But, the response now is:
`
{"jsonrpc":"2.0","id":53,"error":{"code":-32601,"message":"the method linea_estimateGas does not exist/is not available"}}
`

Could you help take a look? Thanks in advance.

**Comment by bgravenorst** [comment]
This method has been temporarily disabled. I raised an issue to update the docs accordingly.
